/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as BillingConfirmRouteImport } from './routes/billing.confirm'
import { Route as ClassIdRouteImport } from './routes/class.$id'
import { Route as LectureIdRouteImport } from './routes/lecture.$id'
import { Route as RecordBoothRouteImport } from './routes/record.booth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingConfirmRoute = BillingConfirmRouteImport.update({
  id: '/billing/confirm',
  path: '/billing/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassIdRoute = ClassIdRouteImport.update({
  id: '/class/$id',
  path: '/class/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureIdRoute = LectureIdRouteImport.update({
  id: '/lecture/$id',
  path: '/lecture/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordBoothRoute = RecordBoothRouteImport.update({
  id: '/booth',
  path: '/booth',
  getParentRoute: () => RecordRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/connect': typeof ConnectRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/record': typeof RecordRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/billing/confirm': typeof BillingConfirmRoute
  '/class/$id': typeof ClassIdRoute
  '/lecture/$id': typeof LectureIdRoute
  '/record/booth': typeof RecordBoothRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/connect': typeof ConnectRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/record': typeof RecordRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/billing/confirm': typeof BillingConfirmRoute
  '/class/$id': typeof ClassIdRoute
  '/lecture/$id': typeof LectureIdRoute
  '/record/booth': typeof RecordBoothRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/connect': typeof ConnectRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/record': typeof RecordRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/usage': typeof UsageRoute
  '/billing/confirm': typeof BillingConfirmRoute
  '/class/$id': typeof ClassIdRoute
  '/lecture/$id': typeof LectureIdRoute
  '/record/booth': typeof RecordBoothRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/connect'
    | '/join'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/record'
    | '/search'
    | '/settings'
    | '/usage'
    | '/billing/confirm'
    | '/class/$id'
    | '/lecture/$id'
    | '/record/booth'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classes'
    | '/connect'
    | '/join'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/record'
    | '/search'
    | '/settings'
    | '/usage'
    | '/billing/confirm'
    | '/class/$id'
    | '/lecture/$id'
    | '/record/booth'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/classes'
    | '/connect'
    | '/join'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/record'
    | '/search'
    | '/settings'
    | '/usage'
    | '/billing/confirm'
    | '/class/$id'
    | '/lecture/$id'
    | '/record/booth'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRoute
  ConnectRoute: typeof ConnectRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecordRoute: typeof RecordRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UsageRoute: typeof UsageRoute
  BillingConfirmRoute: typeof BillingConfirmRoute
  ClassIdRoute: typeof ClassIdRoute
  LectureIdRoute: typeof LectureIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/confirm': {
      id: '/billing/confirm'
      path: '/billing/confirm'
      fullPath: '/billing/confirm'
      preLoaderRoute: typeof BillingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$id': {
      id: '/class/$id'
      path: '/class/$id'
      fullPath: '/class/$id'
      preLoaderRoute: typeof ClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$id': {
      id: '/lecture/$id'
      path: '/lecture/$id'
      fullPath: '/lecture/$id'
      preLoaderRoute: typeof LectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/booth': {
      id: '/record/booth'
      path: '/booth'
      fullPath: '/record/booth'
      preLoaderRoute: typeof RecordBoothRouteImport
      parentRoute: typeof RecordRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecordRouteChildren {
  RecordBoothRoute: typeof RecordBoothRoute
}

const RecordRouteChildren: RecordRouteChildren = {
  RecordBoothRoute: RecordBoothRoute,
}

const RecordRouteWithChildren =
  RecordRoute._addFileChildren(RecordRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRoute,
  ConnectRoute: ConnectRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecordRoute: RecordRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UsageRoute: UsageRoute,
  BillingConfirmRoute: BillingConfirmRoute,
  ClassIdRoute: ClassIdRoute,
  LectureIdRoute: LectureIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
